### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by MuhammadUsamaSiddiqui** [alexrindone/flutter_textfield_search#35]
Support null safety

**Comment by ol-cheesebeard** [comment]
this library is not very useful without null safety in 2022

**Comment by alexrindone** [comment]
@ol-cheesebeard thank you for the kick in the pants! I migrated to null safety. Let me know if you get a chance to use it and have any issues.

**Comment by ol-cheesebeard** [comment]
null safety seems to be working!
