### ISSUE TITLE
only show 2 rows

### ISSUE THREAD

**Issue by EduardEddy** [alexrindone/flutter_textfield_search#36]
In my case, the list only shows two items, and for the users they do not identify that it is a scroll, the input when pressing enter the writing is lost and the search is not done

**Comment by alexrindone** [comment]
@EduardEddy I would love to be able to look into this further. Can you provide a screenshot if you are still leveraging the package? If not I'd still love to see how I can be able to help.

**Comment by Wissperwind** [comment]
Same issue here.
You type something, it finds 10 items, but does display only the first two. The hight of the popup is only enough for exactly two items.
I would whish for twi things:

- Set the hight of the popup - So I can set it to display 5 items for example
- I need an option to display the scroll thumb alsways, not only after scrolling. This would make desktop / web users recognize that there is more to scroll for.

**Comment by lucashegomes** [comment]
Same issue here:

{'label': 'Text' + ' Item 3', 'value': 32} isnt show in suggestion list of textfield_search, just 2 first options

![image](https://user-images.githubusercontent.com/22087562/158662804-007def43-d332-4d60-9085-e89503ca53b7.png)

**Comment by alexrindone** [comment]
resolve with release 0.10.0
